
project "radiance"
kind "StaticLib"
language "C"
defines {
    "lint"
}
files {
    rad_rt.."/Version.c", -- this one is generated on prebuild scripts
    rad_rt.."/ambcomp.c", 
    rad_rt.."/ambient.c",
    rad_rt.."/ambio.c", 
    rad_rt.."/aniso.c", 
    rad_rt.."/ashikhmin.c",
    rad_rt.."/data.c",
    rad_rt.."/dielectric.c",
    rad_rt.."/fprism.c",
    rad_rt.."/freeobjmem.c",
    rad_rt.."/func.c", 
    rad_rt.."/glass.c",
    rad_rt.."/initotypes.c",
    rad_rt.."/m_alias.c",
    rad_rt.."/m_brdf.c",
    rad_rt.."/m_bsdf.c",
    rad_rt.."/m_clip.c",
    rad_rt.."/m_direct.c",
    rad_rt.."/m_mirror.c",
    rad_rt.."/m_mist.c",
    rad_rt.."/mx_func.c",
    rad_rt.."/mx_data.c",
    rad_rt.."/noise3.c",
    rad_rt.."/normal.c",
    rad_rt.."/o_face.c", 
    rad_rt.."/o_cone.c",
    rad_rt.."/o_instance.c",
    rad_rt.."/o_mesh.c",
    rad_rt.."/p_data.c",
    rad_rt.."/p_func.c",
    rad_rt.."/preload.c",
    rad_rt.."/raytrace.c",
    rad_rt.."/renderopts.c",
    rad_rt.."/source.c",
    rad_rt.."/sphere.c",
    rad_rt.."/srcobstr.c",
    rad_rt.."/srcsupp.c",
    rad_rt.."/srcsamp.c",
    rad_rt.."/t_data.c",
    rad_rt.."/t_func.c",
    rad_rt.."/text.c",
    rad_rt.."/pmap.c",
    rad_rt.."/pmapsrc.c",
    rad_rt.."/pmapmat.c",
    rad_rt.."/pmaprand.c",
    rad_rt.."/pmapio.c",        
    rad_rt.."/pmapbias.c",
    rad_rt.."/pmapparm.c",
    rad_rt.."/pmapcontrib.c",
    rad_rt.."/pmapamb.c",
    rad_rt.."/pmapray.c",
    rad_rt.."/pmapopt.c",        
    rad_rt.."/pmapdata.c",
    rad_rt.."/pmapdiag.c",
    rad_rt.."/pmaptype.c",
    rad_rt.."/pmutil.c",
    rad_rt.."/pmcontrib2.c",        
    rad_rt.."/../common/random.h",
    rad_rt.."/../common/platform.h",
    rad_rt.."/func.c",
    rad_rt.."/virtuals.c",
    rad_rt.."/../common/paths.c",
}
targetdir (libs_dir.."/%{cfg.buildcfg}")   
includedirs{
    third_party_dir.."/Radiance/src/**",
    third_party_dir
}
